server {
    listen 80;
    server_name extractor.rosaliacontrerasmoreira.com;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name extractor.rosaliacontrerasmoreira.com;

    ssl_certificate     /etc/nginx/certs/extractor.crt;
    ssl_certificate_key /etc/nginx/certs/extractor.key;

    location / {
        proxy_pass http://extractor:8501;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_read_timeout 86400;
    }
}
